In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('Data (2).csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x)

[['Malaysia' 30.0 32000.0]
 ['Indonesia' 25.0 30000.0]
 ['Singapura' 37.0 50000.0]
 ['Indonesia' 45.0 61000.0]
 ['Singapura' 22.0 25000.0]
 ['Indonesia' 35.0 nan]
 ['Malaysia' 30.0 52000.0]
 ['Singapura' 48.0 79000.0]
 ['Malaysia' nan 83000.0]
 ['Indonesia' 50.0 77000.0]]


In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [10]:
print(x)

[['Malaysia' 30.0 32000.0]
 ['Indonesia' 25.0 30000.0]
 ['Singapura' 37.0 50000.0]
 ['Indonesia' 45.0 61000.0]
 ['Singapura' 22.0 25000.0]
 ['Indonesia' 35.0 54333.333333333336]
 ['Malaysia' 30.0 52000.0]
 ['Singapura' 48.0 79000.0]
 ['Malaysia' 35.77777777777778 83000.0]
 ['Indonesia' 50.0 77000.0]]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [14]:
print(x)

[[0.0 1.0 0.0 30.0 32000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 0.0 1.0 37.0 50000.0]
 [1.0 0.0 0.0 45.0 61000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [1.0 0.0 0.0 35.0 54333.333333333336]
 [0.0 1.0 0.0 30.0 52000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 35.77777777777778 83000.0]
 [1.0 0.0 0.0 50.0 77000.0]]


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [18]:
print(x_train)

[[0.0 1.0 0.0 30.0 52000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [0.0 1.0 0.0 30.0 32000.0]
 [1.0 0.0 0.0 45.0 61000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 35.77777777777778 83000.0]
 [1.0 0.0 0.0 35.0 54333.333333333336]]


In [19]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [20]:
print(x_test)

[[0.0 0.0 1.0 37.0 50000.0]
 [1.0 0.0 0.0 50.0 77000.0]]


In [21]:
print(y_test)

[0 1]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [24]:
print(x_train)

[[0.0 1.0 0.0 -0.4526246511843521 -0.0020242790555111533]
 [0.0 0.0 1.0 -1.3938224818059652 -1.3137571070268148]
 [0.0 1.0 0.0 -0.4526246511843521 -0.9736782257009212]
 [1.0 0.0 0.0 1.3121212812311727 0.43521999693492336]
 [1.0 0.0 0.0 -1.0408732953228603 -1.070843620365462]
 [0.0 0.0 1.0 1.6650704677142776 1.3097085489157925]
 [0.0 1.0 0.0 0.22712933759792422 1.5040393382448745]
 [1.0 0.0 0.0 0.13562399295415617 0.11133534805312013]]


In [25]:
print(x_test)

[[0.0 0.0 1.0 0.37092345060955945 -0.09918967372005216]
 [1.0 0.0 0.0 1.900369925369681 1.2125431542512515]]
